version: "3.4"
services:
    postgres:
      image: postgres:12
      ports:
        - '5432:5432'
      volumes:
        - 'postgres-db-data:/var/lib/postgresql/data'
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=healthcare
        - PG_TRUST_LOCALNET
      networks:
        backend: { aliases: [postgres.backend] }

    app:
      build:
        context: ./
        dockerfile: ./Dockerfile
      image: healthcare/server
      ports:
        - '8080:8080'
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
        - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
        - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      links:
        - "pythonservice"
      depends_on:
        - postgres
        - pythonservice
      volumes:
        - app-logs:/usr/local/tomcat/logs
      networks:
        backend: { aliases: [app.backend] }

    pythonservice:
      image: healthcare/python
      ports:
        - '8888:8888'
      networks:
        backend: { aliases: [pythonservice.backend] }


networks:
  backend:
    driver: bridge

volumes:
  postgres-db-data:
  app-logs: